services:
  sql-server-db:
    container_name: avanpostTask_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
    volumes: 
      - sqlserver:/data/db
volumes:
  sqlserver: